---

- name: ensure Apache2 is installed
  yum: name=httpd state=installed
  become: true
  tags: apache

- name: ensure Apache2 is enabled and started
  service: name=httpd state=started enabled=yes
  become: true
  tags: apache
